# Day 25 Pandas

## Question 1

In [3]:
import pandas as pd

df = pd.read_csv(r'data\hacker_news.csv')

## Question 2

In [8]:
first_5_rows = df.head(5)
first_5_rows

,id,title,url,num_points,num_comments,author,created_at
0,12224879,Interactive Dynamic Video,http://www.interactivedynamicvideo.com/,386,52,ne0phyte,8/4/2016 11:52
1,11964716,Florida DJs May Face Felony for April Fools' W...,http://www.thewire.com/entertainment/2013/04/f...,2,1,vezycash,6/23/2016 22:20
2,11919867,Technology ventures: From Idea to Enterprise,https://www.amazon.com/Technology-Ventures-Ent...,3,1,hswarna,6/17/2016 0:01
3,10301696,Note by Note: The Making of Steinway L1037 (2007),http://www.nytimes.com/2007/11/07/movies/07ste...,8,2,walterbell,9/30/2015 4:12
4,10482257,Title II kills investment? Comcast and other I...,http://arstechnica.com/business/2015/10/comcas...,53,22,Deinos,10/31/2015 9:48

## Question 3

In [11]:
last_5_rows = df.tail(5)
last_5_rows

,id,title,url,num_points,num_comments,author,created_at
20094,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20095,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20096,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20097,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20098,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43

## Qustion 4

In [6]:
title_series = pd.Series(df.iloc[:,1])
title_series

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20094    How Purism Avoids Intels Active Management Tec...
20095            YC Application Translated and Broken Down
20096    Microkernels are slow and Elvis didn't do no d...
20097                        How Product Hunt really works
20098    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20099, dtype: object

## Question 5

In [5]:
# Q5(i) Filter the titles which contain python
python_title = df.loc[df['title'].str.contains('Python', case=False)]
python_title

,id,title,url,num_points,num_comments,author,created_at
102,10974870,From Python to Lua: Why We Switched,https://www.distelli.com/blog/using-lua-for-ou...,243,188,chase202,1/26/2016 18:17
103,11244541,Ubuntu 16.04 LTS to Ship Without Python 2,http://news.softpedia.com/news/ubuntu-16-04-lt...,2,1,_snydly,3/8/2016 10:39
144,10963528,Create a GUI Application Using Qt and Python i...,http://digitalpeer.com/s/c63e,21,1,zoodle,1/24/2016 19:01
196,10716331,How I Solved GCHQ's Xmas Card with Python and ...,http://matthewearl.github.io/2015/12/10/gchq-x...,6,1,kipi,12/11/2015 10:38
436,11895088,"Unikernel Power Comes to Java, Node.js, Go, an...",http://www.infoworld.com/article/3082051/open-...,3,1,syslandscape,6/13/2016 16:23
...,...,...,...,...,...,...,...
19597,12061177,David Beazley Python Concurrency from the Gro...,https://www.youtube.com/watch?v=MCs5OvhV9S4,2,1,bakery2k,7/9/2016 13:05
19852,10988468,Ask HN: How to automate Python apps deployment?,NaN,4,18,aalhour,1/28/2016 14:55
19862,11738470,Moving Away from Python 2,https://asmeurer.github.io/blog/posts/moving-a...,227,275,ngoldbaum,5/20/2016 15:14
19980,12524656,Python vs. Julia Observations,https://medium.com/@Jernfrost/python-vs-julia-...,2,1,blacksmythe,9/18/2016 9:54
19998,11735438,Show HN: Decorating: Animated pulsed for your ...,https://github.com/ryukinix/decorating,3,1,lerax,5/20/2016 3:48

In [4]:
# Q5(ii) Filter the titles which contain JavaScript
js_title = df.loc[df['title'].str.contains('JavaScript', case=False)]
js_title

,id,title,url,num_points,num_comments,author,created_at
267,12352636,Show HN: Hire JavaScript - Top JavaScript Talent,https://www.hirejs.com/,1,1,eibrahim,8/24/2016 15:16
580,10871330,Python integration for the Duktape Javascript ...,https://pypi.python.org/pypi/pyduktape,3,1,stefano,1/9/2016 14:26
811,10741251,Ask HN: Are there any projects or compilers wh...,NaN,1,2,ggonweb,12/15/2015 23:26
1046,11343334,"If you write JavaScript tools or libraries, bu...",https://medium.com/@Rich_Harris/how-to-not-bre...,48,19,callumlocke,3/23/2016 10:54
1093,10422726,Rollup.js: A next-generation JavaScript module...,http://rollupjs.org,57,17,dmmalam,10/21/2015 0:02
...,...,...,...,...,...,...,...
19349,11448301,"Fotorama, a responsive JavaScript photo gallery",http://fotorama.io/,1,1,alexkon,4/7/2016 15:59
19548,12105148,Another Kind of JavaScript Fatigue,http://chrismm.com/blog/the-other-kind-of-java...,9,2,JacksCracked,7/16/2016 3:44
19610,12203508,Lonely programmer detective uncovers the Mozil...,http://stackoverflow.com/a/38677222/984780,29,8,luisperezphd,8/1/2016 16:07
19885,12552131,Ask HN: Best Practices for CSS in a Modern Jav...,NaN,6,6,xwvvvvwx,9/21/2016 20:53
20069,12149183,Show HN: Parse recipe ingredients using JavaSc...,https://github.com/herkyl/ingredients-parser,6,2,zongitsrinzler,7/23/2016 11:35

In [9]:
# Q5(iii) Explore the data and make sense of it
df.describe()

                 id    num_points  num_comments
count  2.009900e+04  20099.000000  20099.000000
mean   1.131755e+07     50.296632     24.803025
std    6.964531e+05    107.110322     56.108639
min    1.017691e+07      1.000000      1.000000
25%    1.070172e+07      3.000000      1.000000
50%    1.128452e+07      9.000000      3.000000
75%    1.192613e+07     54.000000     21.000000
max    1.257898e+07   2553.000000   1733.000000